import os
import argparse
import shutil

# Define the mapping of new = old replacements
CLASSNAME_MAP = {
    "KPLIB_ace": "KP_liberation_ace",
    "KPLIB_ace_crates": "KP_liberation_ace_crates",
    "KPLIB_addBoat": "KP_liberation_boat_classname",
    "KPLIB_addHeli": "KP_liberation_little_bird_classname",
    "KPLIB_aiResupplySources": "KP_liberation_ace_crates",
    "KPLIB_allLandVeh_classes": "KPLIB_allLandVeh_classes",
    "KPLIB_arsenal": "KP_liberation_arsenal",
    "KPLIB_arsenalAllowedExtension": "KP_liberation_allowed_items_extension",
    "KPLIB_arsenalBackpacks": "GRLIB_arsenal_backpacks",
    "KPLIB_arsenalBlacklist": "blacklisted_from_arsenal",
    "KPLIB_arsenalItems": "GRLIB_arsenal_items",
    "KPLIB_arsenalMagazines": "GRLIB_arsenal_magazines",
    "KPLIB_arsenalWeapons": "GRLIB_arsenal_weapons",
    "KPLIB_b_addHeli": "KP_liberation_little_bird_classname",
    "KPLIB_b_addBoat": "KP_liberation_boat_classname",
    "KPLIB_b_airControl": "KP_liberation_air_vehicle_building",
    "KPLIB_b_airSlots": "KPLIB_airSlots",
    "KPLIB_b_allSquads": "KPLIB_b_allSquads",
    "KPLIB_b_arsenal": "Arsenal_typename",
    "KPLIB_b_crateAmmo": "KP_liberation_ammo_crate",
    "KPLIB_b_crateFuel": "KP_liberation_fuel_crate",
    "KPLIB_b_crateSupply": "KP_liberation_supply_crate",
    "KPLIB_b_crewUnit": "crewman_classname",
    "KPLIB_b_fobBox": "FOB_box_typename",
    "KPLIB_b_fobBuilding": "FOB_typename",
    "KPLIB_b_fobTruck": "FOB_truck_typename",
    "KPLIB_b_helicopterPilotUnit": "pilot_classname",
    "KPLIB_b_infantry": "infantry_units",
    "KPLIB_b_infantry_classes": "KPLIB_b_infantry_classes",
    "KPLIB_b_largeStorage": "KP_liberation_large_storage_building",
    "KPLIB_b_logiStation": "KP_liberation_recycle_building",
    "KPLIB_b_logiTruck": "KP_liberation_truck_classname",
    "KPLIB_b_mobileRespawn": "Respawn_truck_typename",
    "KPLIB_b_objectsDeco": "buildings",
    "KPLIB_b_potato01": "huron_typename",
    "KPLIB_b_slotHeli": "KP_liberation_heli_slot_building",
    "KPLIB_b_slotPlane": "KP_liberation_plane_slot_building",
    "KPLIB_b_smallStorage": "KP_liberation_small_storage_building",
    "KPLIB_b_squadAA": "blufor_squad_aa",
    "KPLIB_b_squadAT": "blufor_squad_at",
    "KPLIB_b_squadInf": "blufor_squad_inf",
    "KPLIB_b_squadLight": "blufor_squad_inf_light",
    "KPLIB_b_squadNames": "squads_names",
    "KPLIB_b_squadPara": "blufor_squad_para",
    "KPLIB_b_squadRecon": "blufor_squad_recon",
    "KPLIB_b_support_classes": "KPLIB_b_support_classes",
    "KPLIB_b_vehAir": "air_vehicles",
    "KPLIB_b_vehHeavy": "heavy_vehicles",
    "KPLIB_b_vehLight": "light_vehicles",
    "KPLIB_b_vehStatic": "static_vehicles",
    "KPLIB_b_vehSupport": "support_vehicles",
    "KPLIB_b_vehToUnlock": "elite_vehicles",
    "KPLIB_c_units": "civilians",
    "KPLIB_c_vehicles": "civilian_vehicles",
    "KPLIB_battlegroup_clearance": "KP_liberation_battlegroup_clearance",
    "KPLIB_battlegroup_size": "GRLIB_battlegroup_size",
    "KPLIB_cap_battlegroup": "GRLIB_battlegroup_cap",
    "KPLIB_cap_enemySide": "GRLIB_sector_cap",
    "KPLIB_cap_patrol": "GRLIB_patrol_cap",
    "KPLIB_cap_playerSide": "GRLIB_blufor_cap",
    "KPLIB_civ_rep": "KP_liberation_civ_rep",
    "KPLIB_civilians_amount": "GRLIB_KPLIB_c_units_amount",
    "KPLIB_civinfo_chance": "KP_liberation_civinfo_chance",
    "KPLIB_civinfo_duration": "KP_liberation_civinfo_duration",
    "KPLIB_civinfo_intel": "KP_liberation_civinfo_intel",
    "KPLIB_civinfo_max": "KP_liberation_civinfo_max",
    "KPLIB_civinfo_min": "KP_liberation_civinfo_min",
    "KPLIB_civinfo_task_chance": "KP_liberation_civinfo_task_chance",
    "KPLIB_civinfo_task_duration": "KP_liberation_civinfo_task_duration",
    "KPLIB_civrep_debug": "KP_liberation_civrep_debug",
    "KPLIB_clearances": "KP_liberation_clearances",
    "KPLIB_collisionIgnoreObjects": "GRLIB_ignore_colisions_when_building",
    "KPLIB_color_enemy": "GRLIB_color_enemy",
    "KPLIB_guerilla_strength": "KP_liberation_guerilla_strength",
    "KPLIB_logistics": "KP_liberation_logistics",
    "KPLIB_color_enemyActive": "GRLIB_color_enemy_bright",
    "KPLIB_color_player": "GRLIB_color_friendly",
    "KPLIB_config": "kp_liberation_config",
    "KPLIB_convoy_ambush_chance": "KP_liberation_convoy_ambush_chance",
    "KPLIB_convoy_ambush_duration": "KP_liberation_convoy_ambush_duration",
    "KPLIB_cr_building_penalty": "KP_liberation_cr_building_penalty",
    "KPLIB_cr_kill_penalty": "KP_liberation_cr_kill_penalty",
    "KPLIB_cr_resistance_penalty": "KP_liberation_cr_resistance_penalty",
    "KPLIB_cr_sector_gain": "KP_liberation_cr_sector_gain",
    "KPLIB_cr_vehicle_penalty": "KP_liberation_cr_vehicle_penalty",
    "KPLIB_cr_wounded_chance": "KP_liberation_cr_wounded_chance",
    "KPLIB_cr_wounded_gain": "KP_liberation_cr_wounded_gain",
    "KPLIB_defended_buildingpos_part": "GRLIB_defended_buildingpos_part",
    "KPLIB_endgame": "GRLIB_endgame",
    "KPLIB_enemyReadiness": "combat_readiness",
    "KPLIB_fnc_isCapitalActive": "KPLIB_fnc_isBigtownActive",
    "KPLIB_force_redeploy": "GRLIB_force_redeploy",
    "KPLIB_fuel_max": "KP_liberation_fuel_max",
    "KPLIB_fuel_neutral": "KP_liberation_fuel_neutral",
    "KPLIB_fuel_normal": "KP_liberation_fuel_normal",
    "KPLIB_height_halo": "KPLIB_range_fob",
    "KPLIB_large_storage_positions": "KP_liberation_large_storage_positions",
    "KPLIB_logiTruck": "KP_liberation_truck_classname",
    "KPLIB_medical_facilities": "KP_liberation_medical_facilities",
    "KPLIB_medical_vehicles": "KP_liberation_medical_vehicles",
    "KPLIB_militaryAlphabet": "military_alphabet",
    "KPLIB_o_aaSpecialist": "opfor_aa",
    "KPLIB_o_ammoContainer": "opfor_ammo_container",
    "KPLIB_o_ammoTruck": "opfor_ammo_truck",
    "KPLIB_o_armyVehicles": "opfor_vehicles",
    "KPLIB_o_armyVehiclesLight": "opfor_vehicles_low_intensity",
    "KPLIB_o_atSpecialist": "opfor_at",
    "KPLIB_o_battleGrpVehicles": "opfor_battlegroup_vehicles",
    "KPLIB_o_battleGrpVehiclesLight": "opfor_battlegroup_vehicles_low_intensity",
    "KPLIB_o_engineer": "opfor_engineer",
    "KPLIB_o_flag": "opfor_flag",
    "KPLIB_o_fuelContainer": "opfor_fuel_container",
    "KPLIB_o_fuelTruck": "opfor_fuel_truck",
    "KPLIB_o_grenadier": "opfor_grenadier",
    "KPLIB_o_heavyGunner": "opfor_heavygunner",
    "KPLIB_o_helicopters": "opfor_choppers",
    "KPLIB_o_inf_classes": "KPLIB_o_inf_classes",
    "KPLIB_o_machinegunner": "opfor_machinegunner",
    "KPLIB_o_marksman": "opfor_marksman",
    "KPLIB_o_medic": "opfor_medic",
    "KPLIB_o_militiaInfantry": "militia_squad",
    "KPLIB_o_militiaVehicles": "militia_vehicles",
    "KPLIB_o_mrap": "opfor_mrap",
    "KPLIB_o_mrapArmed": "opfor_mrap_armed",
    "KPLIB_o_officer": "opfor_officer",
    "KPLIB_o_paratrooper": "opfor_paratrooper",
    "KPLIB_o_planes": "opfor_air",
    "KPLIB_o_rifleman": "opfor_rifleman",
    "KPLIB_o_riflemanLAT": "opfor_rpg",
    "KPLIB_o_sentry": "opfor_sentry",
    "KPLIB_o_sharpshooter": "opfor_sharpshooter",
    "KPLIB_o_sniper": "opfor_sniper",
    "KPLIB_o_squadLeader": "opfor_squad_leader",
    "KPLIB_o_squadStd": "KPLIB_o_squadStd",
    "KPLIB_o_teamLeader": "opfor_team_leader",
    "KPLIB_o_transportHeli": "opfor_transport_helo",
    "KPLIB_o_transportTruck": "opfor_transport_truck",
    "KPLIB_o_transportTruckAmmo": "opfor_ammobox_transport",
    "KPLIB_o_troopTransports": "opfor_troup_transports",
    "KPLIB_objectInits": "kp_objectInits",
    "KPLIB_param_adaptive": "GRLIB_adaptive_opfor",
    "KPLIB_param_aggressivity": "GRLIB_csat_aggressivity",
    "KPLIB_param_autodanger": "GRLIB_autodanger",
    "KPLIB_param_difficulty": "GRLIB_difficulty_modifier",
    "KPLIB_param_fatigue": "GRLIB_fatigue",
    "KPLIB_param_fog": "KP_liberation_fog_param",
    "KPLIB_param_halo": "GRLIB_halo_param",
    "KPLIB_param_highCommand": "KP_liberation_high_command",
    "KPLIB_param_logistic": "KP_liberation_ailogistics",
    "KPLIB_param_mapMarkers": "KP_liberation_mapmarkers",
    "KPLIB_param_maxFobs": "GRLIB_max_fobs",
    "KPLIB_param_mobileRespawn": "KP_liberation_mobilerespawn",
    "KPLIB_param_permissions": "GRLIB_permissions_param",
    "KPLIB_param_playerMenu": "KP_liberation_playermenu",
    "KPLIB_param_restart": "KP_liberation_restart",
    "KPLIB_param_supportModule": "KP_liberation_suppMod",
    "KPLIB_param_supportModule_arty": "KPLIB_suppMod_arty",
    "KPLIB_param_supportModule_req": "KPLIB_suppMod_req",
    "KPLIB_param_tutorial": "KP_liberation_tutorial",
    "KPLIB_param_unitcap": "GRLIB_unitcap",
    "KPLIB_param_vanillaFog": "KP_liberation_fog_param",
    "KPLIB_param_weaponSway": "KPLIB_sway",
    "KPLIB_param_zeusCommander": "KP_liberation_commander_zeus",
    "KPLIB_permissions": "GRLIB_permissions",
    "KPLIB_preset_blufor": "KP_liberation_preset_blufor",
    "KPLIB_preset_civilians": "KP_liberation_preset_KPLIB_c",
    "KPLIB_preset_opfor": "KP_liberation_preset_opfor",
    "KPLIB_preset_resistance": "KP_liberation_preset_resistance",    
    "KPLIB_presetCivilians": "KPLIB_preset_civilians",
    "KPLIB_presetEnemy": "KPLIB_preset_opfor",
    "KPLIB_presetResistance": "KPLIB_preset_resistance",
    "KPLIB_production": "KP_liberation_production",
    "KPLIB_radioTowerClassnames": "KPLIB_radioTowerClassnames",
    "KPLIB_range_fob": "GRLIB_fob_range",
    "KPLIB_range_radioTowerScan": "GRLIB_radiotower_size",
    "KPLIB_range_sectorActivation": "GRLIB_sector_size",
    "KPLIB_range_sectorCapture": "GRLIB_capture_size",
    "KPLIB_recycling_percentage": "GRLIB_recycling_percentage",
    "KPLIB_resistance_ambush_chance": "KP_liberation_resistance_ambush_chance",
    "KPLIB_resistance_at_chance": "KP_liberation_resistance_at_chance",
    "KPLIB_resistance_sector_chance": "KP_liberation_resistance_sector_chance",
    "KPLIB_resistance_tier2": "KP_liberation_resistance_tier2",
    "KPLIB_resistance_tier3": "KP_liberation_resistance_tier3",
    "KPLIB_respawn_loadout": "GRLIB_respawn_loadout",
    "KPLIB_respawn_marker": "GRLIB_respawn_marker",
    "KPLIB_r_facegear": "KP_liberation_guerilla_facegear",
    "KPLIB_r_headgear_1": "KP_liberation_guerilla_headgear_1",
    "KPLIB_r_headgear_2": "KP_liberation_guerilla_headgear_2",
    "KPLIB_r_headgear_3": "KP_liberation_guerilla_headgear_3",
    "KPLIB_r_uniforms_1": "KP_liberation_guerilla_uniforms_1",
    "KPLIB_r_uniforms_2": "KP_liberation_guerilla_uniforms_2",
    "KPLIB_r_uniforms_3": "KP_liberation_guerilla_uniforms_3",
    "KPLIB_r_units": "KP_liberation_guerilla_units",
    "KPLIB_r_vehicles": "KP_liberation_guerilla_vehicles",
    "KPLIB_r_vests_1": "KP_liberation_guerilla_vests_1",
    "KPLIB_r_vests_2": "KP_liberation_guerilla_vests_2",
    "KPLIB_r_vests_3": "KP_liberation_guerilla_vests_3",
    "KPLIB_r_weapons_1": "KP_liberation_guerilla_weapons_1",
    "KPLIB_r_weapons_2": "KP_liberation_guerilla_weapons_2",
    "KPLIB_r_weapons_3": "KP_liberation_guerilla_weapons_3",
    "KPLIB_save_interval": "KP_liberation_save_interval",
    "KPLIB_save_key": "GRLIB_save_key",
    "KPLIB_secondary_missions_costs": "GRLIB_secondary_missions_costs",
    "KPLIB_secondary_objective_impact": "GRLIB_secondary_objective_impact",
    "KPLIB_sectors_active": "active_sectors",
    "KPLIB_sectors_all": "sectors_allSectors",
    "KPLIB_sectors_capital": "sectors_bigtown",
    "KPLIB_sectors_fob": "GRLIB_all_fobs",
    "KPLIB_sectors_player": "blufor_sectors",
    "KPLIB_side_civilian": "GRLIB_side_civilian",
    "KPLIB_side_enemy": "GRLIB_side_enemy",
    "KPLIB_side_player": "GRLIB_side_friendly",
    "KPLIB_side_resistance": "GRLIB_side_resistance",
    "KPLIB_small_storage_positions": "KP_liberation_small_storage_positions",
    "KPLIB_storageBuildings": "KPLIB_storageBuildings",
    "KPLIB_surrender_chance": "GRLIB_surrender_chance",
    "KPLIB_transportConfigs": "KPLIB_transportConfigs",
    "KPLIB_vehicle_to_military_base_links:": "GRLIB_vehicle_to_military_base_links",
    "KPLIB_vulnerability_timer": "GRLIB_vulnerability_timer",
    "KPLIB_whitelist_cmdrActions": "KPLIB_commander_actions",
    "KPLIB_whitelist_cmdrSlot": "GRLIB_whitelisted_steamids",
    "KPLIB_whitelist_supportModule": "KP_liberation_suppMod_whitelist",
}

def replace_text_in_file(file_path, dry_run=False):
    """Reads a file, replaces old classnames with new ones, and writes back the updated content."""
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()
    
    updated_content = content
    for new, old in CLASSNAME_MAP.items():
        updated_content = updated_content.replace(old, new)
    
    if content != updated_content:
        print(f"[MODIFY] {file_path}")
        if not dry_run:
            backup_path = file_path + ".bak"
            shutil.copy(file_path, backup_path)  # Create a backup before modifying
            with open(file_path, 'w', encoding='utf-8') as file:
                file.write(updated_content)

def process_directory(directory, extensions=None, dry_run=True):
    """Recursively scans files in a directory and applies classname replacements."""
    for root, _, files in os.walk(directory):
        for file in files:
            if extensions and not file.endswith(tuple(extensions)):
                continue
            file_path = os.path.join(root, file)
            try:
                replace_text_in_file(file_path, dry_run=dry_run)
            except Exception as e:
                print(f"[ERROR] Failed to process {file_path}: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Batch update classnames in Arma 3 scripts.")
    parser.add_argument("directory", help="Root directory to scan for files.")
    parser.add_argument("--extensions", nargs="+", default=None, help="Filter by file extensions (e.g., sqf hpp cfg)")
    parser.add_argument("--dry-run", action="store_true", help="Simulate changes without modifying files.")
    
    args = parser.parse_args()
    
    process_directory(args.directory, extensions=args.extensions, dry_run=args.dry_run)
    
    if args.dry_run:
        print("[DRY-RUN COMPLETE] No files were modified.")
    else:
        print("[UPDATE COMPLETE] All files were modified and backed up.")
